---
title: 影视
author: 范叶亮
date: '2017-12-04'
lastmod: '`r Sys.Date()`'
slug: cn/movies
description: '共鸣，情愫，观念，认知，体验，情怀'
disable_author_date: true
disable_donate: true
disable_comments: true
disable_adsense: true
---

## 共鸣，情愫，观念，认知，体验，情怀

```{r setup, include=F}
library(plyr)
library(tidyverse)
library(lubridate)
library(knitr)
options(knitr.kable.NA = '')

source('../scripts/common/utils.R')
```

```{r moive_list, echo=F, message=F, warning=F, results = 'asis'}
output_col_names <- c(
    'IMDB ID',
    'DOUBAN ID',
    '名称',
    '导演',
    '主演',
    'IMDB 评分',
    '豆瓣评分',
    '打个分'
)

movie_list <- read_tsv(
    '../data/cn/movie-list.tsv',
    col_types = 'cccccccccDDdddiD')

movie_table <- function(movies) {
    which_year <- movies[1, ]$release_year
    which_year <- gen_which_year(which_year)
    header_ <- paste0('<h2>', which_year, '</h2>')
    table_ <- movies %>%
        arrange(desc(release_date), directors, name_zh) %>%
        select(c('imdb_id_html', 'douban_id_html',
                 'name_zh_html', 'directors', 'casts',
                 'imdb_rating_html', 'douban_rating_html', 'rating')) %>%
        setNames(output_col_names) %>%
        kable("html", escape = F, table.attr = 'class="movie-table"') %>%
        clean_html_table()
    footer_ <- '<br/>'
    
    tibble(table_ = paste0(header_, table_, footer_))
}

split_top_n_concat <- function(string, pattern, n) {
    res <- NA
    
    if (!is.na(string)) {
        res <- string %>%
            str_split(pattern, simplify = T) %>%
            as.character %>%
            head(n)
        
        if (n != length(str_split(string, pattern, simplify = T))) {
            res <- c(res, ' ...')
        }
        
        res <- paste(res, collapse = pattern)
    }
    
    res
}
split_top_n_concat <- Vectorize(split_top_n_concat)

movie_list %>%
    mutate(
        directors = directors %>% split_top_n_concat(',', 1),
        casts = casts %>% split_top_n_concat(',', 3),
        release_year = year(release_date),
        imdb_id_html = gen_imdb_id_html(imdb_id),
        douban_id_html = gen_douban_id_html(douban_id),
        name_zh_html = gen_linked_text_html(name_zh, blog_link),
        imdb_rating_html = gen_movie_imdb_rating_link_html(
            imdb_rating, imdb_id),
        douban_rating_html = gen_movie_douban_rating_link_html(
            douban_rating, douban_id)) %>%
    ddply(.(release_year), movie_table) %>%
    arrange(desc(release_year)) %>%
    select(table_) %>%
    unlist %>%
    cat
```

```{r update_movie_info, eval=F, include=F}
movie_list_columns <- c(
    'imdb_id', 'douban_id', 'blog_link', 'name_zh', 'name',
    'directors', 'casts', 'countries', 'genres',
    'release_date', 'watch_date', 'imdb_rating', 'douban_rating', 'rating',
    'auto_update', 'updated_date')
auto_update_colunms <- c(
    'name_zh', 'name', 'directors', 'casts', 'countries', 'genres',
    'release_date', 'imdb_rating', 'douban_rating')

movie_list_auto_update <- movie_list %>%
    filter(auto_update == 1 & (Sys.Date() - updated_date > 30)) %>%
    select(-auto_update_colunms)

movie_list_manual_update <- movie_list %>%
    filter(auto_update == 0 | (Sys.Date() - updated_date <= 30)) %>%
    select(movie_list_columns)

movie_list_auto_update <- movie_list_auto_update %>%
    mutate(imdb_rating = get_movie_imdb_rating(imdb_id)) %>%
    mutate(douban_info = map(douban_id, crawl_movie_douban_info)) %>%
    unnest_wider(douban_info)

movie_list_auto_update %>%
    mutate(updated_date = Sys.Date(),
           imdb_rating = as.numeric(imdb_rating),
           douban_rating = as.numeric(douban_rating)) %>%
    union_all(movie_list_manual_update) %>%
    select(movie_list_columns) %>%
    arrange(desc(release_date)) %>%
    write_tsv('../data/cn/movie-list.tsv')
```
