---
title: 影视
author: 范叶亮
date: '2017-12-04'
lastmod: '`r Sys.Date()`'
slug: videos
disable_author_date: true
disable_donate: true
disable_comments: true
disable_adsense: true
---

## 「共鸣，情愫，观念，认知，体验，情怀」

```{r setup, include=F}
library(plyr)
library(tidyverse)
library(lubridate)
library(knitr)
options(knitr.kable.NA = '')

source('../scripts/share/douban-utils.R')
source('../scripts/share/imdb-utils.R')
source('../scripts/share/render-utils.R')
```

```{r moive_list, echo=F, message=F, warning=F, results = 'asis'}
output_col_names <- c(
    'IMDB ID',
    'DOUBAN ID',
    '名称',
    '导演',
    '主演',
    'IMDB 评分',
    '豆瓣评分',
    '打个分'
)

video_list <- read_tsv(
    '../static/data/videos.tsv',
    col_types = 'ccccccccDDldddiD')

video_table <- function(videos) {
    which_year <- videos[1, ]$release_year
    which_year <- gen_which_year(which_year)
    header_ <- paste0('<h2>', which_year, '</h2>')
    table_ <- videos %>%
        arrange(desc(release_date), directors, title) %>%
        select(c('imdb_id_html', 'douban_id_html',
                 'title_html', 'directors', 'actors',
                 'imdb_rating_html', 'douban_rating_html', 'rating')) %>%
        setNames(output_col_names) %>%
        kable("html", escape = F, table.attr = 'class="video-table"') %>%
        clean_html_table()
    footer_ <- '<br/>'
    
    tibble(table_ = paste0(header_, table_, footer_))
}

split_top_n_concat <- function(string, pattern, n) {
    res <- NA
    
    if (!is.na(string)) {
        res <- string %>%
            str_split(pattern, simplify = T) %>%
            as.character %>%
            head(n)
        
        if (n != length(str_split(string, pattern, simplify = T))) {
            res <- c(res, ' ...')
        }
        
        res <- paste(res, collapse = pattern)
    }
    
    res
}
split_top_n_concat <- Vectorize(split_top_n_concat)

video_list %>%
    mutate(
        directors = directors %>% split_top_n_concat(', ', 1),
        actors = actors %>% split_top_n_concat(', ', 3),
        release_year = year(release_date),
        imdb_id_html = gen_imdb_id_html(imdb_id),
        douban_id_html = gen_douban_id_html(douban_id),
        title_html = gen_linked_text_html(title, blog_link),
        imdb_rating_html = gen_video_imdb_rating_link_html(
            imdb_rating, imdb_id),
        douban_rating_html = gen_video_douban_rating_link_html(
            douban_rating, douban_id)) %>%
    ddply(.(release_year), video_table) %>%
    arrange(desc(release_year)) %>%
    select(table_) %>%
    unlist %>%
    cat
```

```{r update_video_info, eval=F, include=F}
video_list_columns <- c(
    'imdb_id', 'douban_id', 'blog_link', 'title', 'directors', 'actors',
    'countries', 'genres', 'release_date', 'watch_date', 'is_tv',
    'imdb_rating', 'douban_rating', 'rating', 'auto_update', 'updated_date')
auto_update_colunms <- c(
    'title', 'directors', 'actors', 'countries', 'genres',
    'release_date', 'is_tv', 'imdb_rating', 'douban_rating')

video_list_auto_update <- video_list %>%
    filter(auto_update == 1 & (Sys.Date() - updated_date > 30)) %>%
    select(-all_of(auto_update_colunms))

video_list_manual_update <- video_list %>%
    filter(auto_update == 0 | (Sys.Date() - updated_date <= 30)) %>%
    select(all_of(video_list_columns))

video_list_auto_update <- video_list_auto_update %>%
    mutate(imdb_rating = get_video_imdb_rating(imdb_id)) %>%
    mutate(douban_info = map(douban_id, get_video_douban_info)) %>%
    unnest_wider(douban_info, names_repair = 'universal')

video_list_auto_update_succeed <- video_list_auto_update %>%
    filter(!is.na(douban_rating)) %>%
    select(all_of(video_list_columns))

video_list_auto_update_failed <- video_list %>%
    filter(douban_id %in% video_list_auto_update$douban_id) %>%
    filter(!douban_id %in% video_list_auto_update_succeed$douban_id) %>%
    select(all_of(video_list_columns))

video_list_auto_update_succeed %>%
    mutate(updated_date = Sys.Date(),
           imdb_rating = as.numeric(imdb_rating),
           douban_rating = as.numeric(douban_rating)) %>%
    union_all(video_list_auto_update_failed) %>%
    union_all(video_list_manual_update) %>%
    arrange(desc(release_date)) %>%
    write_tsv('../static/data/videos.tsv')
```
